BootStrap: docker
From: nvidia/cuda:9.0-cudnn7-runtime-ubuntu16.04

#---------------------------------------------------------------------
%labels
#---------------------------------------------------------------------
MAINTAINER Wolfgang Resch

#---------------------------------------------------------------------
%environment
#---------------------------------------------------------------------
export PATH=/bin:/usr/bin:/usr/local/bin:/usr/local/cuda/bin:
export LC_ALL=C

#---------------------------------------------------------------------
%post
#---------------------------------------------------------------------

apt-get update
apt-get install -y libhdf5-dev graphviz locales python3-dev python3-pip
apt-get clean
pip3 install --upgrade pip
apt-get update

python3 -m pip install tensorflow-gpu==1.8.0
python3 -m pip install keras==2.1.6
python3 -m pip install Pillow scikit-learn pandas matplotlib notebook ipython

# create some generic mount points
mkdir /mnt/data /mnt/input /mnt/output /mnt/ref /mnt/code /mnt/work
